title: Pablo Lima
description: Personal Academic Site
email: lima.pablohs@gmail.com
description: >-
  Cientista de Dados em Formação
baseurl: ""
url: "https://limapablo.com"
theme: "minimal-mistakes-jekyll"
github_username: limapablo
markdown: kramdown
theme: minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
